### ISSUE TITLE
Diseñar un logo para la aplicación

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#11]
## Descripción

Creación de un logo sencillo que nos funcione para darle algo de personalidad al proyecto. Este logo deberá poder usarse en imágenes grandes, pequeñas, modo oscuro y estar en formato `.svg` en caso de necesitar insertarlo, reescalarlo o recolorearlo de forma programatica en el frontend con SvelteKit

## Objetivos

- [x] Realizar una propuesta de logo.
- [ ] Elegir un logo de entre las propuestas.

**Comment by RancheritoMcfly** [comment]
![Logo_pirita_1](https://github.com/UpVent/Pirita/assets/51002292/c69637e9-9e47-4778-8517-ef75c3941203)

**Comment by RancheritoMcfly** [comment]
![Logo_Pirita_v2](https://github.com/UpVent/Pirita/assets/51002292/a4fdb3cf-951f-4777-bfc1-0bc3e6ba8a8c)

**Comment by RancheritoMcfly** [comment]
![Logo_Pirita_3](https://github.com/UpVent/Pirita/assets/51002292/03a65708-aeea-4481-86c9-8137ce0d85e3)

**Comment by Adolf97** [comment]
# Hola.

Propongo este diseño de logo, también.

Me regresé a lo que comentó Ranche, de usar el color de la pirita, que es como un dorado; y le dejé las líneas como de wifi arriba del carro, como para dar a entender que es una app de rastreo. Igual si sienten que es demasiado, me dicen.
[Propuesta de logo](https://looka.com/s/126518923)

Otra cosa es que sí me gustaría que pudiéramos combinarlo con azul, por lo que les comentaba de que psicológicamente genera confianza. Encontré una imagen con una paleta de colores que me pareció que los combina muy bien.
[Paleta de colores propuesta](https://www.pinterest.com.mx/pin/54606214220197712/)

### A ver qué les parece

**Comment by RancheritoMcfly** [comment]
<img width="821" alt="Logo_Pirita" src="https://github.com/UpVent/Pirita/assets/51002292/fd3e3e33-2dbc-42df-b0dd-17236954c5f1">

**Comment by RancheritoMcfly** [comment]
<img width="400" alt="Logo_Pirita_v5" src="https://github.com/UpVent/Pirita/assets/51002292/12349393-9cec-4e46-9b3e-c372cf103a4d">

**Comment by RancheritoMcfly** [comment]
<img width="820" alt="Logo_Pirita" src="https://github.com/UpVent/Pirita/assets/51002292/3e5dab53-f65d-44ef-83ce-e89df36ea980">

Esta es la propuesta final. este es el bueno.

**Comment by VentGrey** [comment]
Será ese último.
