### ISSUE TITLE
Elegir una paleta de colores para el proyecto.

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#15]
## Descripción

Dado que el proyecto usará bootstrap como framework web para CSS, gracias al tree-shaking de css podemos tratar de definir los colores para los componentes que deseamos. En este caso podemos tomar dos caminos. Podemos elegir entre la paleta de colores pastel de catppucchin, una propia o usar los colores de bootstrap como tal.

## Objetivos

- [ ] Elijo la paleta de colores de bootstrap.
- [x] Elijo la paleta de colores de catppucchin.
- [ ] Quiero nuestra propia paleta de colores
- [ ] Presentar los colores oficiales de la paleta de colores elegida en hexadecimal y en formato `rgb`

**Comment by RancheritoMcfly** [comment]
Esta es la propuesta armada con la colorimetría de Catpuccin. 
![Piritas UpVent](https://github.com/UpVent/Pirita/assets/51002292/7c5f3fe0-25e3-475e-81d3-eab8552445e1)

**Comment by RancheritoMcfly** [comment]
Propuesta de paleta de colores nueva: 
![imagen_2023-05-11_134832142](https://github.com/UpVent/Pirita/assets/51002292/4febf4ca-7c4d-469e-b2a6-07d390709a02)
