### ISSUE TITLE
Proponer un diagrama de funcionamiento

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#16]
## Descripción

En términos simples, un cuadro de cualquier forma, dibujo o diagrama con el funcionamiento deseado del proyecto y la forma percibida de como funcionaría en producción. 

Debemos crear un diagrama de lo que tenemos en mente y alinear nuestras ideas a un proyecto en común.

## Objetivos

- [x] Presentar un diagrama de funcionamiento (RancheritoMcFly)
- [x] Presentar un diagrama de funcionamiento (VentGrey)
- [x] Presentar un diagrama de funcionamiento (ErnestoRdS)

**Comment by RancheritoMcfly** [comment]
Generé este flujo de trabajo con base en el diseño que hizo @Adolf97 
Es necesario cumplir otras pantallas para arrojo de error por registro o fallo.
También falta la vista de operador o trabajador.


![imagen_2023-05-10_154735596](https://github.com/UpVent/Pirita/assets/51002292/ac6b5290-8441-4e50-ba4b-c20f3bca0da4)
