### ISSUE TITLE
Definir pantallas del frontend para el usuario final

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#2]
## Descripción

El objetivo es diseñar una interfaz de usuario atractiva y fácil de usar, que permita a los usuarios interactuar con nuestra aplicación de manera intuitiva y eficiente. Para lograr esto, deberemos definir las distintas pantallas que el usuario podrá ver, así como las funcionalidades que estarán disponibles en cada una de ellas. 📝🤖

- [x] Definir pantallas que el usuario final podrá ver, como la pantalla de inicio, perfil del usuario, lista de vehículos, conductores, reportes de turno, inicio de sesión, emisión de tickets, etc.
- [x] Diseñar las interfaces de usuario para cada pantalla, incluyendo los botones, menús, formularios y otros elementos necesarios.
- [x] Identificar y definir las funcionalidades que estaran disponibles en cada pantalla, como el registro de usuario, la búsqueda de productos, la visualización de detalles de un producto, etc.
- [x] Asegurarnos de que la interfaz de usuario sea fácil de usar, intuitiva y atractiva.

**Comment by Adolf97** [comment]
### Hola chavos!

Anexo el enlace para que puedan checar el diseño que se me ocurrió. Cualquier comentario es bienvenido, jeje.

[Figma - Diseño](https://www.figma.com/file/H76O6Laqe0HrvuC6B0ilOHuC/Untitled?type=design&t=E93dOtrmnU7dVEZE-0)

**Comment by VentGrey** [comment]
Hay un pequeño typo jajaja, el proyecto es "Pirita" no "Piritas". 

PD: :exploding_head: nice design.

**Comment by Adolf97** [comment]
Listo! Ya hice el cambio de "Piritas" a "Pirita".

Ya con la colorimetría que propuso Ranche, voy a empezar a pasar las pantallas ya a svelte.
