### ISSUE TITLE
Crear una página de 404 personalizada.

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#51]
No dejemos las rutas por defecto, la ruta 404 debería ser manejada por Svelte y servir un error 404 para proteger la API de jugar con las rutas.

**Comment by Adolf97** [comment]
# Propuesta de Página 404

Hola, ésta es mi propuesta para la página del error 404
[Error 404](https://www.figma.com/file/yfVL2jqErAVo5hkX5yoJIb/Untitled?type=design&node-id=0-1&t=z5CbQ7DqWA2JtrCv-0)
