### ISSUE TITLE
Los modelos están mal y no permiten la ejecución continua.

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#65]
Estoy tarugo hasta las nubes y de regreso, el modelo conductor tiene una tilde en el campo `Comisión`, esto está causando problemas con gorm, pues no puede encontrar la tabla con la tilde.

**Comment by ErnestoRdS** [comment]
### Ánimo, no pasa nada, todos nos puede pasar **UwU**
Ya actualicé el modelo, en un momento hago el PR.
