### ISSUE TITLE
Propuesta I de diagrama ER para el servicio

### ISSUE THREAD

**Issue by VentGrey** [UpVent/Pirita#9]
## Descripción

Deberá diseñarse una propuesta de un diagrama ER para que la aplicación funcione correctamente, idealmente debería estar explicado y justificada su forma.

## Objetivos

- [x] Crear un diagrama ER propuesto para la BD de la aplicación.

**Comment by ErnestoRdS** [comment]
**SQLite no cuenta con un tipo de dato arreglo, aún ando trabajando en crear la consulta para ver cómo sacar el monto que le toca al conductor para poder sumarlo en el pago final.**
Los atributos tachados es porque las tablas podrían funcionar sin ellos.

![Image](https://user-images.githubusercontent.com/35742450/236331113-ac83321b-02a9-4a5a-b926-9ee8adeba181.jpeg)
